apiVersion: v1
kind: Service
metadata:
  name: s3gw-ui-service
  namespace: s3gw-system
spec:
  selector:
    app.aquarist-labs.io/name: s3gw-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
