apiVersion: v1
kind: Secret
metadata:
  name: s3gw-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: MDU1NWIzNTY1NGFkMTY1NmQ4MDQ=
  AWS_SECRET_ACCESS_KEY: aDdHaHh1QkxUcmxoVlV5eFNQVUtVVjhyLzJFSTRuZ3FKeEQ3aUJkQllMaHdsdU4zMEphVDNRPT0=
  AWS_ENDPOINTS: aHR0cDovL3MzZ3ctc2VydmljZS5zM2d3LXN5c3RlbTo4MC8= # http://s3gw-service.s3gw-system:80/
