apiVersion: v1
kind: Service
metadata:
  name: s3gw-service
  namespace: s3gw-system
spec:
  selector:
    app.aquarist-labs.io/name: s3gw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7480
