dictionaryDefinitions:
  - name: s3gw
    path: docs/dicts/s3gw.dict
    addWords: true
  - name: errno
    path: docs/dicts/errno.dict
    addWords: true
  - name: misc
    path: docs/dicts/misc.dict
    addWords: true
dictionaries:
  - s3gw
  - errno
  - misc
