---
version: "3.4"
services:
  s3gw:
    image: quay.io/s3gw/s3gw:latest
    restart: always
    command:
      - "--rgw-backend-store"
      - "sfs"
    ports:
      - "7480:7480"
    environment:
      RGW_DEFAULT_USER_ACCESS_KEY: "test"
      RGW_DEFAULT_USER_SECRET_KEY: "test"
    volumes:
      - data:/data

  s3gw-ui:
    image: quay.io/s3gw/s3gw-ui:latest
    restart: always
    stop_signal: SIGINT
    depends_on:
      - s3gw
    ports:
      - "8080:8080"
    environment:
      RGW_SERVICE_URL: "http://localhost:3080"

  proxy:
    image: docker.io/nginx:latest
    restart: always
    depends_on:
      - s3gw-ui
    ports:
      - "80:80"
      - "3080:3080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  data:
