site_name: s3gw Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
nav:
  - Introduction: "index.md"
  - Quickstart: "quickstart.md"
  - "Installation & setup":
      - Using a Helm chart: "helm-charts.md"
      - "s3gw with Longhorn setup":
          - K3s Setup: "env-k3s.md"
          - K8s Setup: "env-k8s.md"
  - "Contributing":
      - Contributing: "contributing.md"
  - "Development manual":
      - "Architecture":
          - Developing the S3 Gateway: "developing.md"
      - "Build instructions":
          - Building the s3gw container image: "build.md"
          - Building the s3gw-UI image: "build-ui.md"
      - "Testing":
          - Testing the s3gw: "testing.md"
      - UI: "ui.md"
      - Roadmap: "roadmap.md"
      - S3 API compatibility table: "s3-compatibility-table.md"
      - "Team decisions":
          - Use Markdown Any Decision Records: "decisions/0000-use-markdown-any-decision-records.md"
          - Reorganize Documentation: "decisions/0001-reorganize-documentation.md"
  - "About & license":
      - Repositories: "s3gw-repos.md"
      - License: "license.md"
