site_name: s3gw Documentation
theme:
  name: readthedocs
  highlightjs: true
markdown_extensions:
  - admonition
plugins:
  - search
  - external-markdown
nav:
  - Introduction: "index.md"
  - Quickstart: "quickstart.md"
  - Roadmap: "roadmap.md"
  - "Installation & setup":
      - Using a Helm chart: "helm-charts.md"
      - K8s & K3s setup: "s3gw-with-k8s-k3s.md"
  - "Contributing":
      - Contributing: "contributing.md"
  - "Development manual":
      - Developing the S3 Gateway: "developing.md"
      - Testing the s3gw: "testing.md"
      - UI: "ui.md"
      - S3 API compatibility table: "s3-compatibility-table.md"
  - "About & license":
      - Repositories: "s3gw-repos.md"
      - License: "license.md"
  - "Team decisions":
      - Use Markdown Any Decision Records: "decisions/0000-use-markdown-any-decision-records.md"
      - Reorganize Documentation: "decisions/0001-reorganize-documentation.md"
      - s3gw Storage Backend: "decisions/0002-s3gw-storage-backend.md"
      - SFS SAL Backend Design: "decisions/0003-sfs.md"
      - Release Captain: "decisions/0004-release-captain.md"
      - Project Labels: "decisions/0005-project-labels.md"
      - Git branches tags: "decisions/0006-git-branches-tags.md"
      - Release process: "decisions/0007-release-process.md"
