site_name: s3gw Project Documentation
repo_url: https://github.com/aquarist-labs/s3gw
repo_name: aquarist-labs/s3gw
theme:
  name: material
  logo: https://raw.githubusercontent.com/aquarist-labs/s3gw/main/assets/images/s3gw-logo.png
  highlightjs: true
  features:
    - navigation.instant
markdown_extensions:
  - admonition

plugins:
  - search
  - external-markdown
nav:
  - Introduction: "index.md"
  - Quickstart: "quickstart.md"
  - Roadmap: "roadmap.md"
  - "Installation & setup":
      - Using a Helm chart: "helm-charts.md"
      - K8s & K3s setup: "s3gw-with-k8s-k3s.md"
  - "Contributing":
      - Contributing: "contributing.md"
  - "Development manual":
      - Developing the S3 Gateway: "developing.md"
      - Testing the s3gw: "testing.md"
      - UI: "ui.md"
      - S3 API compatibility table: "s3-compatibility-table.md"
  - "About & license":
      - Repositories: "s3gw-repos.md"
      - License: "license.md"
  - "Team decisions":
      - Use Markdown Any Decision Records: "decisions/0000-use-markdown-any-decision-records.md"
      - Reorganize Documentation: "decisions/0001-reorganize-documentation.md"
      - s3gw Storage Backend: "decisions/0002-s3gw-storage-backend.md"
      - SFS SAL Backend Design: "decisions/0003-sfs.md"
      - Release Captain: "decisions/0004-release-captain.md"
      - Project Labels: "decisions/0005-project-labels.md"
      - Git branches tags: "decisions/0006-git-branches-tags.md"
      - Release process: "decisions/0007-release-process.md"
      - Pull Requests and Code Review Guide: "decisions/0008-pull-requests-code-review-guide.md"
  - "Design documents":
      - UI Backend: "design/0001-ui-backend.md"
  - "Release notes":
      - v0.1.0: "release-notes/s3gw-v0.1.0.md"
      - v0.2.0: "release-notes/s3gw-v0.2.0.md"
      - v0.3.0: "release-notes/s3gw-v0.3.0.md"
      - v0.4.0: "release-notes/s3gw-v0.4.0.md"
      - v0.5.0: "release-notes/s3gw-v0.5.0.md"
      - v0.6.0: "release-notes/s3gw-v0.6.0.md"
      - v0.7.0: "release-notes/s3gw-v0.7.0.md"
      - v0.8.0: "release-notes/s3gw-v0.8.0.md"
      - v0.9.0: "release-notes/s3gw-v0.9.0.md"
      - v0.9.1: "release-notes/s3gw-v0.9.1.md"
      - v0.10.0: "release-notes/s3gw-v0.10.0.md"
      - v0.11.0: "release-notes/s3gw-v0.11.0.md"
      - v0.12.0: "release-notes/s3gw-v0.12.0.md"
      - v0.13.0: "release-notes/s3gw-v0.13.0.md"
      - v0.14.0: "release-notes/s3gw-v0.14.0.md"
      - v0.15.0: "release-notes/s3gw-v0.15.0.md"
      - v0.16.0: "release-notes/s3gw-v0.16.0.md"
      - v0.17.0: "release-notes/s3gw-v0.17.0.md"
