apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.aquarist-labs.io/name: s3gw
  name: s3gw
  namespace: s3gw-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.aquarist-labs.io/name: s3gw
  strategy: {}
  template:
    metadata:
      labels:
        app.aquarist-labs.io/name: s3gw
    spec:
      containers:
        - name: s3gw
          image: ##S3GW_IMAGE##
          imagePullPolicy: ##S3GW_IMAGE_PULL_POLICY##
          args: ["--rgw-backend-store", $(RGW_BACKEND_STORE), "--debug-rgw", $(DEBUG_RGW)]
          envFrom:
            - configMapRef:
                name: s3gw-config
            - secretRef:
                name: s3gw-secret
          volumeMounts:
          - name: s3gw-lh-store
            mountPath: /data
          ports:
            - containerPort: 7480
      volumes:
      - name: s3gw-lh-store
        persistentVolumeClaim:
          claimName: s3gw-pvc
