apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3gw-pvc
  namespace: s3gw-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi
