- name: Longhorn/s3gw Traefik ingress deploy
  hosts: traefik
  tasks:

    - name: Apply ingresses configuration
      command: "{{ item }}"
      with_items:
        - kubectl apply -f /home/{{ user }}/ingress-nginx/longhorn-ingress.yaml
        - kubectl apply -f /home/{{ user }}/ingress-nginx/s3gw-ingress.yaml
