- name: Install k8s Packages
  hosts: all
  become: true
  tasks:

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_facts['eth1']['ipv4']['address'] }}
        create: yes

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Setting kubectl alias and enabling kubectl bash completion
      command: "{{ item }}"
      with_items:
          - /bin/bash -c "sudo echo 'source <(kubectl completion bash)' >> /home/{{ user }}/.bashrc"
          - /bin/bash -c "sudo touch /etc/bash_completion.d/kubectl"
          - /bin/bash -c "sudo chmod 777 /etc/bash_completion.d/kubectl"
          - /bin/bash -c "kubectl completion bash > /etc/bash_completion.d/kubectl"
          - /bin/bash -c "sudo echo 'alias k=kubectl' >> /home/{{ user }}/.bashrc"
          - /bin/bash -c "sudo echo 'complete -F __start_kubectl k' >> /home/{{ user }}/.bashrc"

- name: Kubeadm
  hosts: admins
  become: true
  tasks:
    - name: Initialize Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="{{ ansible_facts['eth1']['ipv4']['address'] }}" --apiserver-cert-extra-sans="{{ ansible_facts['eth1']['ipv4']['address'] }}" --node-name admin --pod-network-cidr={{ cidr_net }}/16 --ignore-preflight-errors=Swap

    - name: Setup kubeconfig for user
      command: "{{ item }}"
      with_items:
          - mkdir -p /home/{{ user }}/.kube
          - cp -i /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config
          - chown {{ user }}:docker /home/{{ user }}/.kube/config

    - name: Copy content of /etc/kubernetes/admin.conf
      command: "cat /etc/kubernetes/admin.conf"
      register: admin_conf

    - name: Copy kubeconfig to local file
      local_action: copy content="{{ admin_conf.stdout }}" dest=./admin.conf

    - name: Install Calico pod network
      become: false
      command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

    - name: Patching Calico custom-resources.yaml
      command: "{{ item }}"
      with_items:
          - mkdir -p /home/{{ user }}/calico
          - wget https://docs.projectcalico.org/manifests/custom-resources.yaml -P /home/{{ user }}/calico
          - sed -i s/192.168.0.0/{{ cidr_net }}/g /home/{{ user }}/calico/custom-resources.yaml

    - name: Install Calico pod network
      become: false
      command: kubectl create -f /home/{{ user }}/calico/custom-resources.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Join
  hosts: workers
  become: true
  tasks:
    - name: Copy join command inside vm
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join node to cluster
      command: sh /tmp/join-command.sh

    - name: Setup kubeconfig for user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/{{ user }}/.kube

    - name: Copy kubeconfig to local file
      copy: src=./admin.conf dest=/home/{{ user }}/.kube/config mode=0777

- name: Probe admin
  hosts: admins
  tasks:
    - name: Wait for admin to become ready
      command: kubectl get nodes admin
      register: result
      until: result.stdout.find("NotReady") == -1
      retries: 25
      delay: 5

- name: Untaint admin
  hosts: solo_admins
  tasks:
    - name: Untaint admin for pod scheduling
      command: "{{ item }}"
      with_items:
          - kubectl taint node --all node-role.kubernetes.io/master-
          - kubectl taint node --all node-role.kubernetes.io/control-plane-
