- name: Deploy NGINX controller
  hosts: nginx
  tasks:

    - name: Install NGINX controller
      command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml

    - name: Copy nginx ingresses cfg to local dir
      copy: src=../ingress-nginx dest=/home/{{ user }} mode=0777

    - name: Create a Service for the Ingress Controller Pods
      command: kubectl apply -f /home/{{ user }}/ingress-nginx/nginx-nodeport.yaml

    - name: Wait NGINX controller to become ready, this could take a while ...
      command: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=30s
      register: result
      until: result.rc == 0
      retries: 20
      delay: 2
