apiVersion: v1
kind: Secret
metadata:
  name: s3gw-secret
  namespace: longhorn-system
type: Opaque
data:
  # The Base64 encoded s3gw default user access key.
  AWS_ACCESS_KEY_ID: ##RGW_DEFAULT_USER_ACCESS_KEY_BASE64##
  # The Base64 encoded s3gw default user secret key.
  AWS_SECRET_ACCESS_KEY: ##RGW_DEFAULT_USER_SECRET_KEY_BASE64##
  # The Base64 encoded URL http://s3gw-service.s3gw-system:80/
  AWS_ENDPOINTS: aHR0cDovL3MzZ3ctc2VydmljZS5zM2d3LXN5c3RlbTo4MC8=
