---
name: Build Environment
on:

  push:
    branches:
      - "main"

  workflow_call:
    inputs:
      tag:
        description: "A tag to use for the container image."
        required: false
        type: string
      ref:
        description: "The git ref to checkout and build."
        required: false
        default: "main"
        type: string
      dockerhub_username:
        description: "A username to use for push to dockerhub"
        required: true
        default: ${{ secrets.DOCKERHUB_USERNAME }}
        type: string
      dockerhub_token:
        description: "A token to use for push to dockerhub"
        required: true
        default: ${{ secrets.DOCKERHUB_TOKEN }}
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_token }}

      - name: Set Container Image Tag
        id: tag
        run: |
          if [ -z "${{ inputs.tag }}" ]; then
            echo ::set-output name=tag::"latest"
          else
            echo ::set-output name=tag::"${{ inputs.tag }}"
          fi

      - name: Build Buildenv Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ inputs.dockerhub_username }}/buildenv-radosgw:${{ steps.tag.outputs.tag }}
          file: 'build/Dockerfile.build-radosgw'
          context: 'build'
