---
name: Build Environment
on:
  push:
    branches:
      - "main"

    # Only run this if the respective Dockerfiles have changed
    paths:
      - "tools/build/*"
      - ".github/workflows/build-environment.yaml"

  workflow_dispatch:  # Allow this workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - build-radosgw
          - build-run-radosgw
          - build-run-radosgw-tests

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build image ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            quay.io/s3gw/${{ matrix.dockerfile }}:latest
            quay.io/s3gw/${{ matrix.dockerfile }}:${{ github.sha }}
          file: 'tools/build/Dockerfile.${{ matrix.dockerfile }}'
          context: 'tools/build'
