---
name: Debug
on:
  - workflow_dispatch

jobs:
  lint:
    runs-on: self-hosted
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Context
        run: |
          docker context create builder

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builder

      - name: Sleep
        run: |
          sleep 1d
